name : my-first workflow
on :
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : clone app
        uses : actions/checkout@v5
      - name : setup node
        uses : actions/setup-node@v5
        with :
          node-version: 24
      - name : install dependencies
        run : npm ci
      - name : build app
        run : npm run build
      - name: Inspect runner
        run: |
            echo "Current directory:"
            pwd
        
            echo "Files:"
            ls -la
        
            echo "Node version:"
            node --version
        
            echo "NPM version:"
            npm --version
        