name : my-first workflow
on :
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : clone app
        uses : actions/checkout@v5
      - name : setup node
        uses : actions/setup-node@v5
        with :
          node-version: 24
      - name : install dependencies
        run : npm ci
      - name : build app
        run : npm run build
      - name : build docker img
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-ci-cd:v1 .
      - name : docker login
        uses : docker/login-action@v3
        with :
          username : ${{ secrets.DOCKERHUB_USERNAME }}
          password : ${{ secrets.DOCKERHUB_TOKEN }}
      - name : push docker img
        run : docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-ci-cd:v1
      - name : deploy to ec2
        uses : appleboy/ssh-action@v1.2.2
        with :
          host : ${{ secrets.EC2_HOST }}
          username : ${{ secrets.EC2_USER }}
          key : ${{ secrets.EC2_SSH_KEY }}
          script : |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-ci-cd:v1
            sudo docker stop react-app || true
            sudo docker rm react-app || true
            sudo docker run -d --name react-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/react-ci-cd:v1
          
      
        